apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-helpdesk
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nikhilrs99-web/ai-helpdesk-platform.git'
    targetRevision: main
    path: infrastructure/helm/helpdesk
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helpdesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
